service: cantekwebapp-be

frameworkVersion: '3'

plugins:
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs20.x # nodeJS version project is using
  region: us-east-1 # your region is

functions:
  api:
    handler: dist/lambda.handler #Lambda entrypoint
    events: #Endpoints to application controllers into the app
      - http:
          path: /
          method: GET
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
            allowCredentials: false
