service: CANTEK-WEPAPP-BE
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    SERVICE: ${self:service}
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region,'us-east-2'}
    NO_COLOR: ${env:NO_COLOR}
    IS_DDB_LOCAL: ${env:IS_DDB_LOCAL,'false'}
    JWT_SECRET: ${env:JWT_SECRET}
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:*
        # - Effect: Allow
        #   Action:
        #     - "s3:GetObject"
        #     - "s3:PutObject"
        #     - "s3:PutObjectAcl"
        #     - "s3:DeleteObject"
        #     - "s3:ListBucket"
        # Resource:
        #   - "arn:aws:s3:::cantek-files/*"

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline
  - serverless-jetpack
  - serverless-dotenv-plugin
custom:
  serverless-dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: false

functions:
  index-function:
    handler: src/index.handler
    events:
      - http:
          cors: true
          path: "{proxy+}"
          method: any

resources:
  - ${file(resource/dynamodb.yml)}
  # - ${file(resource/s3.yml)}
